playList:
    path: '/playlists'
    controller: App\Controller\PlayListController::getAllPlayListAction
    methods: [ GET ]

detail:
    path: '/playlists/{id}'
    controller: App\Controller\PlayListController::getDetailPlayListAction
    methods: [ GET ]